name: CI/CD Pipeline

on: 
  push: 
    branches:
      - main

jobs: 
  build: 
    name: Build Frontend Artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'
      
      - name: Install Dependencies
        run: |
          cd frontend
          npm install
          
      - name: Build Artifact
        run: |
          cd frontend
          npm run build
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: frontend-artifact
          path: frontend/build

  audit:
    name: Audit Frontend Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run audit on production dependencies
        run: npm audit --production

  lint:
    name: Ensure Code Style
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'
      
      - name: Install Dependencies
        run: cd frontend && npm install

      - name: Lint code
        run: cd frontend && npm run lint

  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'

      - name: Install Dependencies
        run: cd frontend && npm install

      - name: Run unit tests
        run: cd frontend && npm run test-ci

  deploy:
    name: Deploy Frontend Artifact
    runs-on: ubuntu-latest
    needs:
      - build
      - lint
      - test
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: frontend-artifact
          path: frontend-build

      - name: Deploy to Production
        run: echo "Deploying frontend to production..."

  verify:
    name: Verify Successful Deployment
    runs-on: ubuntu-latest
    needs:
      - deploy
    if: success()
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Frontend Smoke Test
        run: |
          export TEST_URL="http://example.com"
          cd frontend/e2e
          npm install
          npm run smoke
