name: CI/CD Pipeline

on: 
  push: 

permissions:
  contents: read
  pages: write
  id-token: write

jobs: 
  build: 
    name: Build Artifact
    runs-on: ubuntu-latest
    needs: audit
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'
      
      - name: Install Dependencies
        run: |
          npm i
      - name: Build artifact
        run: |
          npm run build
      
      - uses: actions/upload-pages-artifact@v1
        with: 
          path: build
      
  audit:
    name: Audit Deps
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run the audit on production deps only
        run: npm audit --omit=dev
