name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm ci

    - name: Build artifact
      run: npm run build

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: build-artifact
        path: build/

  check-dependencies:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm ci

    - name: Check dependencies for security issues
      run: npm audit --audit-level=high

  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm ci

    - name: Lint code
      run: npm run lint

  static-analysis:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm ci

    - name: Run static analysis
      run: npm run static-analysis

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: build-artifact

    - name: Deploy to server
      run: |
        # Supongamos que tienes configurado un servidor SSH para el despliegue
        echo "Deploying to server..."
        scp -r build/ user@yourserver.com:/path/to/deploy/
        ssh user@yourserver.com 'cd /path/to/deploy && npm install --production && pm2 restart your-app'

  verify:
    needs: deploy
    runs-on: ubuntu-latest

    steps:
    - name: Verify deployment
      run: |
        echo "Verifying deployment..."
