name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    name: Build Frontend Artifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'npm'

      - name: Install Dependencies
        run: |
          cd frontend
          npm ci

      - name: Build Artifact
        run: |
          cd frontend
          npm run build

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: frontend-build
          path: frontend/build

  audit:
    name: 🪄 Audit Frontend Deps
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run Audit
        run: npm ci && npm audit --only=production

  lint:
    name: 📎 Ensure Code Style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'npm'

      - name: Install Dependencies
        run: cd frontend && npm ci

      - name: Lint Code
        run: cd frontend && npm run lint

  test:
    name: 🪛 Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'npm'

      - name: Install Dependencies
        run: cd frontend && npm ci

      - name: Run Tests
        run: cd frontend && npm run test-ci

  static-analysis:
    name: 🔬 Run Static Code Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: github/codeql-action/init@v1
        with:
          languages: javascript

      - name: Build
        run: cd frontend && npm ci && npm run build

  deploy:
    name: 📦 Deploy Frontend Artifact
    runs-on: ubuntu-latest
    needs:
      - lint
      - test
      - static-analysis
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: frontend-build
          path: frontend/build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend/build

  verify:
    name: 🧪 Verify Successful Deployment
    needs:
      - deploy
    runs-on: ubuntu-latest
    if: success()
    steps:
      - name: Verify Deployment
        run: |
          echo "Deployment verified!"
